import Head from 'next/head'
import {Inter} from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from "@/components/Banner";
import Image from "next/image";
import Card from "@/components/Card";

import coffeeStores from '../data/coffee-stores.json';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const handleBannerButtonClick = () => {
    console.log('click')
  }

  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner buttonTitle={'View stores nearby'} handleButtonClick={handleBannerButtonClick}/>

        <div className={styles.heroImage}>
          <Image
            src={'/static/hero.png'} alt={'hero img'}
            width={700}
            height={400}
          />
        </div>


        <div className={styles.cardLayout}>
          {coffeeStores.map(store => (
            <Card
              key={store.id}
              href={`/coffee-store/${store.id}`}
              imgURL={store.imgUrl}
              title={store.name}
            />
          ))}
        </div>

      </main>
    </>
  )
}
