import Head from 'next/head'
import {Inter} from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from "@/components/Banner";
import Image from "next/image";
import Card from "@/components/Card";

import coffeeStores from '../data/coffee-stores.json';
import {GetStaticProps, InferGetStaticPropsType, NextPage} from "next";

const inter = Inter({subsets: ['latin']})

type Props = {
  coffeeStoresProps: typeof coffeeStores;
}

const Home: NextPage<Props> = ({coffeeStoresProps}) => {

  console.log(`coffeeStoresProps =`, coffeeStoresProps)
  const handleBannerButtonClick = () => {
    console.log('click')
  }

  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <Banner buttonTitle={'View stores nearby'}
                handleButtonClick={handleBannerButtonClick}/>

        <div className={styles.heroImage}>
          <Image
            src={'/static/hero.png'} alt={'hero img'}
            width={700}
            height={400}
          />
        </div>

        {coffeeStoresProps.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>

            <div className={styles.cardLayout}>
              {coffeeStoresProps.map(store => (
                <Card
                  key={store.id}
                  href={`/coffee-store/${store.id}`}
                  imgURL={store.imgUrl}
                  title={store.name}
                />
              ))}
            </div>
          </>
        )}

      </main>
    </>
  )
}

export default Home;

export const getStaticProps: GetStaticProps<Props> = async (context) => {
  return {
    props: {coffeeStoresProps: coffeeStores}
  }
}
